config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cars do
    collection do
      get 'search'
    end
  end
  # search_cars GET /cars/search(.:format) cars#search
  resources :makes do
    collection do
      get 'search'
    end
  end
  resources :parts do
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "cars#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :make
  has_and_belongs_to_many :parts

  validates :model, presence: true, uniqueness: true, length: {minimum: 2}
  validates :vin, presence: true, uniqueness: true, length: { is: 17},
            format: { with: /\A[0-9A-Z]+\z/, message: "only allows numbers and capital letters"}
  validates_presence_of :make_id, :parts
end

app/models/cars_part.rb
class CarsPart < ApplicationRecord
  belongs_to :part
  belongs_to :car

  validates_associated :car, :part
  validates_uniqueness_of :part_id, :car_id

end

app/models/make.rb
class Make < ApplicationRecord
  has_many :cars

  validates :name, presence: true, uniqueness: true, length: {minimum: 2}
  validates :country, presence: true, length: {minimum: 2}
end

app/models/part.rb
class Part < ApplicationRecord
  has_and_belongs_to_many :cars

  validates :name, presence: true, uniqueness: true, length: {minimum: 2}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
    @makes = Make.all
    @parts = Part.all
  end

  # GET /cars/1/edit
  def edit
    @makes = Make.all
    @parts = Part.all
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @cars = Car.where("model like ?", "%#{params[:query]}%")
    render :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:model, :make_id, :vin, :part_ids => [])
    end
end

app/controllers/makes_controller.rb
class MakesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_make, only: [:show, :edit, :update, :destroy]

  # GET /makes
  # GET /makes.json
  def index
    @makes = Make.all
  end

  # GET /makes/1
  # GET /makes/1.json
  def show
  end

  # GET /makes/new
  def new
    @make = Make.new
  end

  # GET /makes/1/edit
  def edit
  end

  # POST /makes
  # POST /makes.json
  def create
    @make = Make.new(make_params)

    respond_to do |format|
      if @make.save
        format.html { redirect_to @make, notice: 'Make was successfully created.' }
        format.json { render :show, status: :created, location: @make }
      else
        format.html { render :new }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /makes/1
  # PATCH/PUT /makes/1.json
  def update
    respond_to do |format|
      if @make.update(make_params)
        format.html { redirect_to @make, notice: 'Make was successfully updated.' }
        format.json { render :show, status: :ok, location: @make }
      else
        format.html { render :edit }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /makes/1
  # DELETE /makes/1.json
  def destroy
    @make.destroy
    respond_to do |format|
      format.html { redirect_to makes_url, notice: 'Make was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @makes = Make.where("name like ?", "%#{params[:query]}%")
    render :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_make
      @make = Make.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def make_params
      params.require(:make).permit(:name, :country, :car_ids => [])
    end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
    @cars = Car.all
  end

  # GET /parts/1/edit
  def edit
    @cars = Car.all
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: 'Part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @parts = Part.where("name like ?", "%#{params[:query]}")
    render :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:name, :car_ids => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>
      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field"><!-- Input car model -->
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field"><!-- Select car make -->
    <%= form.label :make_id %>
    <%= form.collection_select(:make_id, Make.all, :id, :name) %>
  </div>

  <div class="field"><!-- Input car VIN -->
    <%= form.label :vin %>
    <%= form.text_field :vin %>
  </div>
  <div class="field"><!-- Select car parts -->
    <br>
    <%= form.label :part_id %>
    <br>
    <div class="table"><%= form.collection_check_boxes(:part_ids, Part.all, :id, :name) %><br></div>
  </div>

  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<div class="body-content">
  <div class="log-out"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></div>
  <br>

  <!--Navigation bar -->
  <div class="nav-bar active-page"><%= link_to "Cars", cars_url %></div>
  <div class="nav-bar"><%= link_to "Car Makes", makes_url %></div>
  <div class="nav-bar"><%= link_to "Car Parts", parts_url %></div>

  <div class="page-content">
    <h1>Editing Car</h1>

    <%= render 'form', car: @car %>

    <br>
    <div class="links"><%= link_to 'Show', @car %></div>
    <div class="links"><%= link_to 'Back', cars_path %></div>
  </div>
</div>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<div class="body-content">
  <div class="log-out"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></div>
  <br>

  <!--Navigation bar -->
  <div class="nav-bar active-page"><%= link_to "Cars", cars_url %></div>
  <div class="nav-bar"><%= link_to "Car Makes", makes_url %></div>
  <div class="nav-bar"><%= link_to "Car Parts", parts_url %></div>

  <div class="page-content">
    <h1>Cars</h1>

    <!--Search function -->
    <%= form_tag(search_cars_url, method: "get") do %>
      <%= label_tag(:query, "Search for car models:") %>
      <%= text_field_tag(:query) %>
      <%= submit_tag("Search") %>
    <% end %>
    <br>

    <table>
      <thead>
        <tr>
          <th>Model</th>
          <th>Make</th>
          <th>Country of Origin</th>
          <th>Vin</th>
          <th colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @cars.each do |car| %>
          <tr>
            <td><%= car.model %></td>
            <td><%= car.make.name %></td>
            <td><%= car.make.country %></td>
            <td><%= car.vin %></td>
            <td class="links"><%= link_to 'Show', car %></td>
            <td class="links"><%= link_to 'Edit', edit_car_path(car) %></td>
            <td class="links"><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <div class="links"><%= link_to 'New Car', new_car_path %></div>
  </div>
</div>

app/views/cars/new.html.erb
<div class="body-content">
  <div class="log-out"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></div>
  <br>

  <!--Navigation bar -->
  <div class="nav-bar active-page"><%= link_to "Cars", cars_url %></div>
  <div class="nav-bar"><%= link_to "Car Makes", makes_url %></div>
  <div class="nav-bar"><%= link_to "Car Parts", parts_url %></div>

  <div class="page-content">
    <h1>New Car</h1>

    <%= render 'form', car: @car %>

    <div class="links"><%= link_to 'Back', cars_path %></div>
  </div>
</div>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<div class="body-content">
  <div class="log-out"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></div>
  <br>

  <!--Navigation bar -->
  <div class="nav-bar active-page"><%= link_to "Cars", cars_url %></div>
  <div class="nav-bar"><%= link_to "Car Makes", makes_url %></div>
  <div class="nav-bar"><%= link_to "Car Parts", parts_url %></div>

  <div class="page-content">
    <h1>Car Details</h1>
    <p>
      <strong>Model:</strong>
      <%= @car.model %>
    </p>

    <p>
      <strong>Make:</strong>
      <%= @car.make.name %>
    </p>

    <p>
      <strong>Country of Origin:</strong>
      <%= @car.make.country %>
    </p>

    <p>
      <strong>Vin:</strong>
      <%= @car.vin %>
    </p>

    <strong>Parts:</strong>
    <ul>
      <% @car.parts.each do |part| %>
        <li><%= part.name %></li>
      <% end %>
    </ul>

    <div class="links"><%= link_to 'Edit', edit_car_path(@car) %></div>
    <div class="links"><%= link_to 'Back', cars_path %></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buildcar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/makes/_form.html.erb
<%= form_with(model: make, local: true) do |form| %>
  <% if make.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(make.errors.count, "error") %> prohibited this make from being saved:</h2>

      <ul>
      <% make.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field"><!-- Input car make  -->
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field"><!-- Input car make country -->
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/makes/edit.html.erb
<div class="body-content">
  <div class="log-out"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></div>
  <br>

  <!--Navigation bar -->
  <div class="nav-bar"><%= link_to "Cars", cars_url %></div>
  <div class="nav-bar active-page"><%= link_to "Car Makes", makes_url %></div>
  <div class="nav-bar"><%= link_to "Car Parts", parts_url %></div>

  <div class="page-content">
    <h1>Editing Car Make</h1>

    <%= render 'form', make: @make %>

    <div class="links"><%= link_to 'Show', @make %></div>
    <div class="links"> <%= link_to 'Back', makes_path %></div>
  </div>
</div>

app/views/makes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="body-content">
  <div class="log-out"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></div>
  <br>

  <!--Navigation bar -->
  <div class="nav-bar"><%= link_to "Cars", cars_url %></div>
  <div class="nav-bar active-page"><%= link_to "Car Makes", makes_url %></div>
  <div class="nav-bar"><%= link_to "Car Parts", parts_url %></div>

  <div class="page-content">
    <h1>Car Makes</h1>

    <!--Search function -->
    <%= form_tag(search_makes_url, method: "get") do %>
      <%= label_tag(:query, "Search for car make:") %>
      <%= text_field_tag(:query) %>
      <%= submit_tag("Search") %>
    <% end %>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Country</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @makes.each do |make| %>
          <tr>
            <td><%= make.name %></td>
            <td><%= make.country %></td>
            <td class="links"><%= link_to 'Show', make %></td>
            <td class="links"><%= link_to 'Edit', edit_make_path(make) %></td>
            <td class="links"><%= link_to 'Destroy', make, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <div class="links"><%= link_to 'New Make', new_make_path %></div>
  </div>
</div>

app/views/makes/new.html.erb
<div class="body-content">
  <div class="log-out"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></div>
  <br>

  <!--Navigation bar -->
  <div class="nav-bar"><%= link_to "Cars", cars_url %></div>
  <div class="nav-bar active-page"><%= link_to "Car Makes", makes_url %></div>
  <div class="nav-bar"><%= link_to "Car Parts", parts_url %></div>

  <div class="page-content">
    <h1>New Car Make</h1>

    <%= render 'form', make: @make %>

    <div class="links"><%= link_to 'Back', makes_path %></div>
  </div>
</div>

app/views/makes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="body-content">
  <div class="log-out"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></div>
  <br>

  <!--Navigation bar -->
  <div class="nav-bar"><%= link_to "Cars", cars_url %></div>
  <div class="nav-bar active-page"><%= link_to "Car Makes", makes_url %></div>
  <div class="nav-bar"><%= link_to "Car Parts", parts_url %></div>

  <div class="page-content">
    <h1>Car Make</h1>
    <p>
      <strong>Name:</strong>
      <%= @make.name %>
    </p>

    <p>
      <strong>Country:</strong>
      <%= @make.country %>
    </p>

    <ul>
      <% @make.cars.each do |car| %>
        <li><%= car.model %></li>
      <% end %>
    </ul>

    <div class="links"><%= link_to 'Edit', edit_make_path(@make) %></div>
    <div class="links"><%= link_to 'Back', makes_path %></div>
  </div>
</div>

app/views/parts/_form.html.erb
<%= form_with(model: part, local: true) do |form| %>
  <% if part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
      <% part.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--Input car make -->
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parts/edit.html.erb
<div class="body-content">
  <div class="log-out"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></div>
  <br>

  <!--Navigation bar -->
  <div class="nav-bar"><%= link_to "Cars", cars_url %></div>
  <div class="nav-bar"><%= link_to "Car Makes", makes_url %></div>
  <div class="nav-bar active-page"><%= link_to "Car Parts", parts_url %></div>

  <div class="page-content">
    <h1>Editing Car Part</h1>

    <%= render 'form', part: @part %>

    <div class="links"><%= link_to 'Show', @part %></div>
    <div class="links"><%= link_to 'Back', parts_path %></div>
  </div>
</div>

app/views/parts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="body-content">
  <div class="log-out"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></div>
  <br>

  <!--Navigation bar -->
  <div class="nav-bar"><%= link_to "Cars", cars_url %></div>
  <div class="nav-bar"><%= link_to "Car Makes", makes_url %></div>
  <div class="nav-bar active-page"><%= link_to "Car Parts", parts_url %></div>

  <div class="page-content">
    <h1>Car Parts</h1>

    <!--Search function -->
    <%= form_tag(search_parts_url, method: "get") do %>
      <%= label_tag(:query, "Search for car parts:") %>
      <%= text_field_tag(:query) %>
      <%= submit_tag("Search") %>
    <% end %>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @parts.each do |part| %>
          <tr>
            <td><%= part.name %></td>
            <td class="links"><%= link_to 'Show', part %></td>
            <td class="links"><%= link_to 'Edit', edit_part_path(part) %></td>
            <td class="links"><%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <div class="links"><%= link_to 'New Part', new_part_path %></div>
  </div>
</div>

app/views/parts/new.html.erb
<div class="body-content">
    <div class="log-out"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></div>
    <br>

    <!--Navigation bar -->
    <div class="nav-bar"><%= link_to "Cars", cars_url %></div>
    <div class="nav-bar"><%= link_to "Car Makes", makes_url %></div>
    <div class="nav-bar active-page"><%= link_to "Car Parts", parts_url %></div>

    <div class="page-content">
    <h1>New Car Part</h1>

    <%= render 'form', part: @part %>

    <div class="links"><%= link_to 'Back', parts_path %></div>
  </div>
</div>

app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="body-content">
  <div class="log-out"><%= link_to 'Log out', destroy_user_session_path, method: :delete %></div>
  <br>

  <!--Navigation bar -->
  <div class="nav-bar"><%= link_to "Cars", cars_url %></div>
  <div class="nav-bar"><%= link_to "Car Makes", makes_url %></div>
  <div class="nav-bar active-page"><%= link_to "Car Parts", parts_url %></div>

  <div class="page-content">
    <h1>Car Part Details</h1>
    <p>
      <strong>Name:</strong>
      <%= @part.name %>
    </p>

    <div class="links"><%= link_to 'Edit', edit_part_path(@part) %></div>
    <div class="links"><%= link_to 'Back', parts_path %></div>
  </div>
</div>